# This action's steps must be synced with preMergeRequestCheck Gradle task's checks to ensure that
# we check required stuff on CI and at the same time developers can run the Gradle task to verify their
# changes before making a PR. This action can be used in more workflows than just PR, since these
# basic pre merge request checks (Detekt, library tests, ...) are fundamental to be checked in
# basically all situations like merging, pushing to dev, etc.
name: Basic preflight check
description: Action that contains basic checks like running Detekt or library tests that are common to multiple workflows

runs:
  using: "composite"
  steps:
    - name: Detekt
      shell: bash
      run: ./gradlew detekt

    - name: Assemble KMP Android
      shell: bash
      run: ./gradlew assembleAndroidMain

    - name: Assemble KMP iOS
      shell: bash
      run: ./gradlew compileKotlinIosSimulatorArm64

    - name: Assemble Android library
      shell: bash
      run: ./gradlew assembleRelease -x :app:assembleRelease

    - name: KMP Android tests
      shell: bash
      run: ./gradlew testAndroidHostTest

    - name: KMP iOS tests
      shell: bash
      run: ./gradlew iosSimulatorArm64Test

    - name: Android library tests
      shell: bash
      run: ./gradlew testReleaseUnitTest -x :app:testReleaseUnitTest

    - name: Binary compatibility check
      shell: bash
      run: ./gradlew checkLegacyAbi

    - name: Build logic tests
      shell: bash
      run: ./gradlew build-logic:logic:test
